'use strict';
(()=>{
const data=window.CANYON_CATALOG;
if(!data?.sections){document.querySelector('#product-sections').textContent='The collection could not load. Please refresh the page.';return;}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validUrl=u=>{try{return ['https:','http:'].includes(new URL(u).protocol)?u:''}catch{return ''}};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number.isInteger(n)?0:2}).format(n);
const storageKey='canyon-home-progress-v1';let storageAvailable=true,progress={};
try{progress=JSON.parse(localStorage.getItem(storageKey)||'{}');if(!progress||Array.isArray(progress)||typeof progress!=='object')progress={}}catch{storageAvailable=false;progress={}}
const items=data.sections.flatMap(s=>s.items.map(i=>({...i,sectionId:String(s.id),sectionTitle:s.title})));const itemMap=new Map(items.map(i=>[i.id,i]));
for(const id of Object.keys(progress)){if(!itemMap.has(id)){delete progress[id];continue}const p=progress[id];if(!p||typeof p!=='object'){delete progress[id];continue}p.quantity=Math.min(999,Math.max(1,Math.round(Number(p.quantity)||1)));p.saved=!!p.saved;p.note=String(p.note||'').slice(0,5000);if(!['Considering','Ready','Ordered','Bringing','Skip'].includes(p.status))p.status='Considering'}
let category='all',view='collection',query='',priority='all',activeId=null,toastTimer;
const labels={arrival:'Move-in',core:'Core setup',later:'Finishing touch'};
const icons={all:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',office:'<rect x="4" y="3" width="16" height="12" rx="1"/><path d="M12 15v5m-5 0h10"/>',living:'<path d="M5 12V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v5M5 19v2m14-2v2M3 11h3v5h12v-5h3v8H3z"/>',dining:'<path d="M3 9h18M5 9v12m14-12v12M7 3v6m10-6v6"/>',coffee:'<path d="M4 7h12v11a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3zM16 8h3a3 3 0 0 1 0 6h-3M7 2v2m5-2v2"/>',kitchen:'<path d="M5 3v8m-3-8v5a3 3 0 0 0 6 0V3M5 11v10M17 3v18m0-18c-5 2-5 9 0 9"/>',bedroom:'<path d="M3 18V6m18 12V6M3 14h18M3 10h18M6 10V7h5v3m2 0V7h5v3M3 18v3m18-3v3"/>',bathroom:'<path d="M3 12h18v3a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5zM5 12V5a3 3 0 0 1 6 0M6 20v2m12-2v2"/>',entry:'<path d="M4 21V3h16v18M8 21V7h8v14M13 14h1"/>',cleaning:'<path d="m14 3-4 9M7 11l7 3-3 8-9-4zM5 16l6 3"/>',essentials:'<path d="M4 7h16v14H4zM8 7V3h8v4M9 14h6m-3-3v6"/>'};
const svg=key=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[key]||icons.essentials}</svg>`;
function state(i){return progress[i.id]||{saved:false,quantity:Number(i.quantity)||1,status:'Considering',note:''}}
function patch(id,change){const i=itemMap.get(id);if(!i)return;progress[id]={...state(i),...change};try{localStorage.setItem(storageKey,JSON.stringify(progress));storageAvailable=true}catch{storageAvailable=false;toast('Browser storage is unavailable. Use Save progress to keep your choices.')}updateCount()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3400)}
function updateCount(){$('#saved-count').textContent=items.filter(i=>state(i).saved).length;$('#storage-notice').textContent=storageAvailable?'Saved on this device only':'Storage unavailable — download progress to keep it'}
function shortTitle(s){return s.shortTitle||s.title.replace(' & personal care','').replace(' & cooking','').replace(' & sleep','').replace('Small household essentials','Essentials')}
function renderTabs(){$('#category-tabs').innerHTML=[{id:'all',title:'All',icon:'all'},...data.sections].map(s=>`<button data-category="${esc(s.id)}" class="${category===String(s.id)?'active':''}" aria-pressed="${category===String(s.id)}">${svg(s.icon)}${esc(shortTitle(s))}</button>`).join('')}
function priceHtml(i){if(i.priceLabel)return `<span class="price">${esc(i.priceLabel)}</span>`;return typeof i.price==='number'&&Number.isFinite(i.price)?`<span class="price">${i.priceFrom?'From ':''}${money(i.price)}</span>`:'<span class="price unknown">Check price ↗</span>'}
function link(url,label,cls=''){const u=validUrl(url);return u?`<a class="${cls}" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${label}</a>`:''}
function photo(i,loading='lazy'){return validUrl(i.image)?`<img src="${esc(i.image)}" alt="${esc(i.name)}" loading="${loading}" decoding="async" referrerpolicy="no-referrer">`:`<div class="image-missing">${svg(data.sections.find(s=>String(s.id)===i.sectionId)?.icon)}<span>${esc(i.role||'Choose after measuring')}</span></div>`}
function card(i,n){const s=state(i);return `<article class="product-card" data-item="${esc(i.id)}"><div class="card-top"><span class="stage-label ${esc(i.stage)}">${esc(i.badge||labels[i.stage]||'Core setup')}</span><button class="save-button ${s.saved?'saved':''}" data-save="${esc(i.id)}" aria-label="${s.saved?'Remove':'Add'} ${esc(i.name)} ${s.saved?'from':'to'} order list" aria-pressed="${s.saved}">${s.saved?'✓':'+'}</button></div><button class="product-image-button" data-detail="${esc(i.id)}" aria-label="View ${esc(i.name)} details">${photo(i,n<3?'eager':'lazy')}</button><div class="card-copy"><div class="brand-line">${esc(i.brand)} <span>·</span> ${esc(i.role)}</div><div class="product-name-row"><button class="product-name" data-detail="${esc(i.id)}">${esc(i.name)}</button>${priceHtml(i)}</div><div class="card-role"><span>${esc(i.finish||'Finish to confirm')}</span><span>${esc(i.quantityNote||`Qty ${Number(i.quantity)||1}`)}</span></div><div class="card-actions"><div class="buy-links">${link(i.url,'Shop ↗')}${link(i.amazonUrl,'Amazon US ↗','amazon-link')}</div><button class="details-link" data-detail="${esc(i.id)}">Details +</button></div></div></article>`}
function matches(i){return(category==='all'||i.sectionId===category)&&(priority==='all'||i.stage===priority)&&(!query||`${i.name} ${i.brand} ${i.role} ${i.why} ${i.sectionTitle}`.toLowerCase().includes(query))}
function renderCollection(){const filtered=items.filter(matches);$('#result-count').textContent=`${filtered.length} ${filtered.length===1?'essential':'essentials'}${category!=='all'?' in this collection':''}`;$('#empty-results').hidden=filtered.length>0;let n=0;$('#product-sections').innerHTML=data.sections.map((s,index)=>{const group=filtered.filter(i=>i.sectionId===String(s.id));if(!group.length)return '';return `<section class="product-section" id="section-${esc(s.id)}"><div class="section-heading"><div><span class="overline">${String(index+1).padStart(2,'0')} / ${group.length} essentials</span><h2>${esc(s.title)}</h2></div><p>${esc(s.summary)}</p></div><div class="product-grid">${group.map(i=>card(i,n++)).join('')}</div></section>`}).join('');bindImageFallbacks();renderTabs()}
function bindImageFallbacks(){ $$('img').forEach(img=>{img.onerror=()=>{if(img.closest('.order-item')){img.remove();return}const fallback=document.createElement('div');fallback.className='image-missing';fallback.innerHTML=svg('essentials')+'<span>Product photos at retailer ↗</span>';img.replaceWith(fallback)}})}
function setView(v,scroll=true){view=v;$('#hero').hidden=v!=='collection';$('#collection').hidden=v!=='collection';$('#orders').hidden=v!=='orders';$('#guide').hidden=v!=='guide';$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-current',b.dataset.view===v?'page':'false')});if(v==='orders')renderOrders();if(scroll)window.scrollTo({top:0,behavior:'instant'});history.replaceState(null,'',v==='collection'?location.pathname:`#${v}`)}
function renderOrders(){const list=items.filter(i=>state(i).saved);const payable=list.filter(i=>!['Bringing','Skip'].includes(state(i).status));const known=payable.filter(i=>typeof i.price==='number');const total=known.reduce((s,i)=>s+i.price*state(i).quantity,0),unknown=payable.length-known.length;const ready=list.filter(i=>state(i).status==='Ready').length,ordered=list.filter(i=>state(i).status==='Ordered').length;$('#order-summary').innerHTML=`<div class="summary-tile"><small>On your list</small><strong>${list.length}</strong><p>Product lines, before quantities</p></div><div class="summary-tile"><small>Known-price subtotal</small><strong>${money(total)}</strong><p>${unknown?`${unknown} unpriced line${unknown===1?'':'s'} excluded`:'Excludes tax and delivery'} · Bringing & Skip excluded</p></div><div class="summary-tile"><small>Ready to order</small><strong>${ready}</strong><p>Set after confirming your choices</p></div><div class="summary-tile"><small>Ordered</small><strong>${ordered}</strong><p>Marked by you</p></div>`;if(!list.length){$('#order-table-wrap').innerHTML='<div class="empty-state"><h2>A little planning. A much easier move.</h2><p>Add products with the + button, then keep quantities and progress here.</p><button class="pill-button dark" data-view="collection">Explore the collection</button></div>';return}$('#order-table-wrap').innerHTML=`<table class="order-table"><thead><tr><th>Essential</th><th>Qty</th><th>Progress</th><th>Unit price</th><th>Line total</th><th>Buy</th><th><span class="visually-hidden">Remove</span></th></tr></thead><tbody>${list.map(i=>{const s=state(i);return `<tr><td><div class="order-item">${validUrl(i.image)?`<img src="${esc(i.image)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:''}<div><button data-detail="${esc(i.id)}">${esc(i.name)}</button><small>${esc(i.brand)} · ${esc(i.role)}</small>${s.note?`<small>${esc(s.note.slice(0,100))}${s.note.length>100?'…':''}</small>`:''}</div></div></td><td><input class="qty-input" type="number" min="1" max="999" value="${s.quantity}" data-quantity="${esc(i.id)}" aria-label="Quantity for ${esc(i.name)}"></td><td><select class="status-select" data-status="${esc(i.id)}" aria-label="Progress for ${esc(i.name)}">${['Considering','Ready','Ordered','Bringing','Skip'].map(v=>`<option ${v===s.status?'selected':''}>${v}</option>`).join('')}</select></td><td>${typeof i.price==='number'?money(i.price):'Check price'}</td><td>${['Bringing','Skip'].includes(s.status)?'—':typeof i.price==='number'?money(i.price*s.quantity):'Not priced'}</td><td><div class="table-links">${link(i.url,'Retailer ↗')}${link(i.amazonUrl,'Amazon US ↗')}</div></td><td><button class="remove-item" data-save="${esc(i.id)}" aria-label="Remove ${esc(i.name)}">×</button></td></tr>`}).join('')}</tbody></table>`;bindImageFallbacks()}
function openDetail(id){const i=itemMap.get(id);if(!i)return;activeId=id;const s=state(i);$('#dialog-content').innerHTML=`<div class="dialog-layout"><div class="dialog-visual">${photo(i,'eager')}</div><div class="dialog-copy"><div class="dialog-brand">${esc(i.brand)} · ${esc(i.role)}</div><h2 id="dialog-title">${esc(i.name)}</h2><div class="dialog-price">${i.priceLabel?esc(i.priceLabel):typeof i.price==='number'?`${i.priceFrom?'From ':''}${money(i.price)}`:'Price to confirm'}</div><div class="price-note">${esc(i.priceNote||'Research price in USD, before tax and shipping. Recheck the selected finish and seller.')}<br>Checked ${esc(i.checked||data.checked||'September 2026')}.</div><p class="dialog-why">${esc(i.why)}</p><dl class="specs"><div><dt>Finish</dt><dd>${esc(i.finish||'Confirm before ordering')}</dd></div><div><dt>Dimensions</dt><dd>${esc(i.dimensions||'See product specification')}</dd></div><div><dt>Planned quantity</dt><dd>${esc(i.quantityNote||i.quantity||1)}</dd></div><div><dt>Stage</dt><dd>${esc(labels[i.stage]||'Core setup')}</dd></div></dl>${i.caveat?`<div class="caveat"><strong>Before ordering</strong><br>${esc(i.caveat)}</div>`:''}<div class="dialog-buy">${link(i.url,'Shop retailer ↗','pill-button dark')}${link(i.amazonUrl,'Amazon US ↗','pill-button')}</div><div class="dialog-actions"><label>Qty <input class="qty-input" type="number" min="1" max="999" value="${s.quantity}" data-quantity="${esc(id)}" aria-label="Quantity for ${esc(i.name)}"></label><button class="pill-button ${s.saved?'':'dark'}" data-dialog-save="${esc(id)}">${s.saved?'✓ On your order list':'Add to order list +'}</button></div>${(i.alternatives||[]).length?`<div class="detail-block"><h3>Worth comparing</h3>${i.alternatives.map(a=>`<div class="alternative">${link(a.url,`${esc(a.name)} ↗`)}<p>${esc(a.why)}</p></div>`).join('')}</div>`:''}<div class="detail-block"><h3>Your note</h3><textarea class="notes-input" id="item-note" placeholder="Chosen finish, measurements, delivery notes…" aria-label="Your private note for this item">${esc(s.note)}</textarea><span class="note-caption">Saved on this device. Add to the order list to include it in your export.</span></div><div class="detail-block"><details><summary>Research & product sources</summary><div class="source-links">${(i.sources||[]).map(s=>link(typeof s==='string'?s:s.url,esc(typeof s==='string'?new URL(s).hostname:s.title||new URL(s.url).hostname)+' ↗')).join('')}${i.imageSource?link(i.imageSource,'Photography source ↗'):''}</div></details></div></div></div>`;bindImageFallbacks();if(!$('#product-dialog').open)$('#product-dialog').showModal();document.body.style.overflow='hidden'}
function closeDetail(){$('#product-dialog').close();document.body.style.overflow='';activeId=null}
function toggleSave(id){const i=itemMap.get(id);if(!i)return;const added=!state(i).saved;patch(id,{saved:added});toast(added?'Added to your order list':'Removed from your order list');renderCollection();if(view==='orders')renderOrders();if(activeId===id){const b=$('[data-dialog-save]');if(b){b.textContent=added?'✓ On your order list':'Add to order list +';b.classList.toggle('dark',!added)}}}
function download(content,type,name){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function csv(all=false){const list=all?items:items.filter(i=>state(i).saved);if(!list.length){toast('Add some essentials to your order list first.');return}const rows=[['Collection','Role','Product','Brand','Quantity','Progress','Stage','Finish','Unit price USD','Line total USD','Price note','Dimensions','Before ordering','Retailer URL','Amazon US URL','Alternatives','Your note']];list.forEach(i=>{const s=state(i);rows.push([i.sectionTitle,i.role,i.name,i.brand,s.quantity,s.status,labels[i.stage],i.finish,i.price??'',typeof i.price==='number'&&!['Bringing','Skip'].includes(s.status)?i.price*s.quantity:'',i.priceNote,i.dimensions,i.caveat,i.url,i.amazonUrl,(i.alternatives||[]).map(a=>`${a.name}: ${a.url}`).join(' | '),s.note])});const cell=v=>{let t=String(v??'');if(/^[=+@\-]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};download('\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8',all?'canyon-complete-checklist.csv':'canyon-order-list.csv')}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){setView(v.dataset.view);return}const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;renderCollection();return}const d=e.target.closest('[data-detail]');if(d){openDetail(d.dataset.detail);return}const s=e.target.closest('[data-save],[data-dialog-save]');if(s){toggleSave(s.dataset.save||s.dataset.dialogSave);return}});
document.addEventListener('change',e=>{if(e.target.matches('[data-quantity]')){const id=e.target.dataset.quantity;const q=Math.min(999,Math.max(1,Math.round(Number(e.target.value)||1)));e.target.value=q;patch(id,{quantity:q});if(view==='orders')renderOrders()}if(e.target.matches('[data-status]')){patch(e.target.dataset.status,{status:e.target.value});renderOrders()}});
document.addEventListener('input',e=>{if(e.target.id==='item-note'&&activeId){patch(activeId,{note:e.target.value.slice(0,5000)});if(view==='orders')renderOrders()}});
$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderCollection()});$('#priority-filter').addEventListener('change',e=>{priority=e.target.value;renderCollection()});$('#reset-filters').onclick=()=>{category='all';query='';priority='all';$('#search').value='';$('#priority-filter').value='all';renderCollection()};$('#focus-search').onclick=()=>{setView('collection',false);$('#search').scrollIntoView({block:'center'});$('#search').focus()};$('.dialog-close').onclick=closeDetail;$('#product-dialog').addEventListener('click',e=>{if(e.target===$('#product-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail()}});$('#product-dialog').addEventListener('close',()=>{document.body.style.overflow='';activeId=null});$('#export-all').onclick=()=>csv(true);$('#export-orders').onclick=()=>csv();$('#backup').onclick=()=>download(JSON.stringify({version:1,exported:new Date().toISOString(),progress},null,2),'application/json','canyon-shopping-progress.json');$('#restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('too large');const imported=JSON.parse(await file.text());if(imported.version!==1||!imported.progress||typeof imported.progress!=='object'||Array.isArray(imported.progress))throw Error('invalid');let count=0;for(const [id,p]of Object.entries(imported.progress)){if(!itemMap.has(id)||!p||typeof p!=='object')continue;patch(id,{saved:!!p.saved,quantity:Math.min(999,Math.max(1,Math.round(Number(p.quantity)||1))),status:['Considering','Ready','Ordered','Bringing','Skip'].includes(p.status)?p.status:'Considering',note:String(p.note||'').slice(0,5000)});count++}renderCollection();renderOrders();toast(`Restored progress for ${count} essentials`)}catch{toast('This is not a valid Canyon progress file.')}e.target.value=''};
$('#total-count').textContent=items.length;$('#research-date').textContent=`Researched ${data.checked||'September 2026'} · Prices in USD`;updateCount();renderCollection();if(['orders','guide'].includes(location.hash.slice(1)))setView(location.hash.slice(1),false);
})();
